### ISSUE TITLE
Has joined the game

### ISSUE THREAD

**Issue by rubenwardy** [luk3yx/minetest-cloaking#1]
`if victim == "singleplayer" then`

should be

`if victim ~= "singleplayer" then`

**Comment by luk3yx** [comment]
Hello,

In singleplayer, the built-in `*** singleplayer joined the game` isn't displayed, therefore, for consistency, the join message must be displayed. In multiplayer, the built-in joined the game message(s) get called, as they are defined in the LUA API.

**Comment by rubenwardy** [comment]
Ah, missed the callback call
