### ISSUE TITLE
Keep the cloaked state between leave/join

### ISSUE THREAD

**Issue by hlqkj** [luk3yx/minetest-cloaking#7]
Would it be nice to save the cloaked state in player meta and re-apply it automatically on next join (ofc hiding the join message too) such that we can connect to the server silently. If agreed, perhaps would be the best to have a setting to enable this feature...

**Comment by luk3yx** [comment]
> Would it be nice to save the cloaked state in player meta and re-apply it automatically on next join (ofc hiding the join message too) such that we can connect to the server silently. If agreed, perhaps would be the best to have a setting to enable this feature...

I think this is a good idea, as long as it's optional so that anyone who doesn't like it can just disable it.
